# Uffizzi extension
x-uffizzi:
  ingress:    # required
    service: loadbalancer
    port: 8080
  continuous_preview:
    share_to_github: true

# Vote applicaiton
services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  worker:
    build: .  # defaults to ./Dockerfile
    deploy:
      x-uffizzi-auto-deploy-updates: false
      resources:
        limits:
          memory: 250M
    x-uffizzi-continuous-preview:      
      deploy_preview_when_pull_request_is_opened: true
      delete_preview_when_pull_request_is_closed: true

  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result#foo-bar  # branch does not exist  
      dockerfile: Dockerfile
      secrets:
        - secret_port

  vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote  # defaults to "Default branch" as set in GitHub (usually main/master)
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      PORT: 8888

  loadbalancer:
    image: nginx:latest
    configs:
      - source: nginx-vote-conf
        target: /etc/nginx/conf.d/vote.conf


# Loadbalancer configuration
configs:
  nginx-vote-conf:
    file: ./vote.conf
    
secrets:
  secret_port:
    external: true    
    name: "PORT"

