# Uffizzi extension
x-uffizzi:
  ingress:    # required
    service: loadbalancer
    port: 80
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

# Vote applicaiton
services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  worker:
    build: .  # defaults to ./Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    build:
      context: https://github.com/UffizziCloud/example-voting-result#main
      dockerfile: Dockerfile

  vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote#main
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M

  loadbalancer:
    image: nginx:latest
    configs:
      - source: nginx-vote-conf
        target: /etc/nginx/conf.d/vote.conf


# Loadbalancer configuration
configs:
  nginx-vote-conf:
    file: ./vote.conf
