services:

  nginx:
    image: nginx:latest
    configs:
      - source: vote-nginx-conf
        target: /etc/nginx/conf.d/vote.conf
        
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 250M

  worker:
    image: uffizziqa.azurecr.io/example-voting-worker:latest
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizziqa.azurecr.io/example-voting-vote:latest
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      PORT: 8888

  result:
    image: uffizziqa.azurecr.io/example-voting-result:latest
    environment:
      PORT: 8088
    
configs:
  vote-nginx-conf:
    file: ./vote.conf
    
continuous_preview:
  deploy_preview_when_image_tag_is_created: true
  tag_pattern: uffizzi_request_*
  delete_preview_after: 1h

ingress:
  service: nginx
  port: 8080
