version: "3"

services:
  nginx:
    image: nginx:latest
    configs:
      - source: vote.conf
        target: /etc/nginx/conf.d
    
  redis:
    image: redis:latest
    ports: ["6379"]
  
  postgres:
    image: postgres:9.6
    deploy: 
      resources:
        limits:
          memory: 250M
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  worker:
    build:
      context:  https://github.com/jpthurman/example-voting-worker:main
      dockerfile: Dockerfile
    deploy: 
      resources:
        limits:
          memory: 250M  
  vote:
    build:
      context:  https://github.com/jpthurman/example-voting-vote:main
      dockerfile: Dockerfile
    deploy: 
      resources:
        limits:
          memory: 250M
          
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  result:
    build:
      context:  https://github.com/jpthurman/example-voting-result:main
      dockerfile: Dockerfile
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
