services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:latest
    configs:
      - source: vote-nginx-conf
        target: /etc/nginx/conf.d/vote.conf

  worker:
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    build:
      context: https://github.com/UffizziCloud/example-voting-vote
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 250M
    environment:
      PORT: 8888

  result:
    image: uffizziqa.azurecr.io/example-voting-result:latest
    environment:
      PORT: 8088

configs:
  vote-nginx-conf:
    file: ./configs/vote.conf

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

ingress:
  service: nginx
  port: 8080
