services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:9.6
    env_file:
      - postgres.env
    deploy:
      resources:
        limits:
          memory: 250M

  nginx:
    image: nginx:latest
    configs:
      - source: vote.conf
        target: /etc/nginx/conf.d

  worker:
    image: uffizziqa.azurecr.io/example-voting-worker:
    deploy:
      resources:
        limits:
          memory: 250M

  vote:
    image: uffizziqa.azurecr.io/example-voting-vote:
    deploy:
      resources:
        limits:
          memory: 250M

  result:
    image: uffizziqa.azurecr.io//example-voting-result:

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

ingress:
  service: nginx
  port: 8080
