version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.0
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: uffizziqa.azurecr.io
          registry-name: uffizziqa
          repo: example-voting-worker
          tag: $CIRCLE_TAG

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - adams-docker-hub

jobs:
 build:
   machine: true

   steps:
     - checkout

     # Login to Docker Hub so we can push later.
     - run: docker login --username $DOCKER_USER --password $DOCKER_PASS

     # build the application image
     - run: docker build -t uffizzicloud/example-worker:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push uffizzicloud/example-worker:$CIRCLE_BRANCH
